/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aparnaswaminathan' at '1/23/16 10:23 AM' with Gradle 2.7
 *
 * @author aparnaswaminathan, @date 1/23/16 10:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
